### PR TITLE
Observe the color panel's target to handle switching between multiple color wells

### PR DESCRIPTION
**Pull request by DarkDust**
When you've got multiple color wells and switch between them by clicking on another color well's button while the color panel remains open, the old color panel doesn't know it's not "active" any more and is still drawing its button in the activated state. So we need to observe the color panel's `target` property and react to the change.

### CODE REVIEW

**Comment by danieljfarrell** [comment]
Have a problem merging this one (because I have left it 3 years... I'm sorry 😭). Want to continue with it?

**Comment by DarkDust** [comment]
No problem, I'm going to look into this tomorrow.

**Comment by DarkDust** [comment]
This PR is obsolete due to #17, where 5d136699e19d0ca0834eb3796143e7fb95cebbd1 contains the changes from this PR. So your repo and mine is now back in sync, thank you very much!

**Comment by danieljfarrell** [comment]
That's great news. Thanks for taking a look and thanks for sending the changes.

**Pull request closed without merging**
